### ISSUE TITLE
pyramid levels in reader api

### ISSUE THREAD

**Issue by toloudis** [bioio-devs/bioio-base#8]
### Feature Description

add some notion of multiresolution levels to the reader api

### Use Case

ome-zarr supports multiresolution levels.  I believe there is a flavor of ome-tiff also.  And czi.

### Solution

This probably requires some extra discussion to design the api but here is an idea:
Add support for ome-zarr first.  Other readers should just always use level 0 (max resolution).
A simple option seems to be to handle it like scenes, where you call set_multiresolution_level, and get_num_multiresolution_levels.
Dimensions for each multiresolution level will be different, of course.

### Alternatives

Perhaps a way to fold it in with dimensions, but that seems less ergonomic.  Each data read request has to be for a particular multiresolution level.   
It would also be interesting for the ome-zarr reader to have a chunk api so you can know your requests are at the chunk boundaries.

**Comment by SeanLeRoy** [comment]
See relevant issue submitted in [aicsimageio](https://github.com/AllenCellModeling/aicsimageio/issues/539)
